version: '3.8'

services:
  server:
    build:
      context: ./server
    ports:
      - "8000:8000"
    environment:
      - EXCHANGE_RATE_API_KEY=a1304752dc74c2929fd62678
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  client:
    build:
      context: ./client
    ports:
      - "5173:5173"
    command: npm run dev -- --host
